# Site settings
name: Henri Partanen
email: partanenhe@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Electrical Engineer, Electro Optics, Optics, Space Tech"
skills: "Electrical Engineer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
#social:
#  - title: linkedin
#    url: n/a
#  - title: medium
#    url: n/a
#  - title: twitter
#    url: n/a
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7c7d7f
  primary-rgb: "33, 150, 243"
  secondary: 212835
  secondary-dark: 212835
  section-tout: e4ebf2



# Build settings
markdown: kramdown
permalink: pretty
